### ISSUE TITLE
Factorio 2.0 / Space age

### ISSUE THREAD

**Issue by theotherbigfoot** [veger/TLBE#61] opened 2024-10-03 08:44 UTC
Alright dude, I was just wondering what your plan was for TLBE with space age coming out. Is the mod going to be updated?

**Comment by veger** [comment] 2024-10-03 14:34
I am planning to update yes.

I don't think there will be major issues with the mod (assuming the planets are just different surfaces), and I am expecting for it to work. But besides the FFF I have no actual information about it, so I guess I'll have to wait until the time is there and hope my hunch is correct. :smile:

**Comment by theotherbigfoot** [comment] 2024-10-03 18:04
I've been given beta access to space age, me and a couple others tried jerry rigging the mod to get it to work (it would be awesome to drop a timelapse on day 1 after the media blackout) but no joy. Several errors, fix one and another pops up. 

That's great that it's gonna be updated, I guess I'll have to wait until the game is on general release before I can start recording again.

**Comment by veger** [comment] 2024-10-03 18:40
Yes, it is unfortunate that there are errors. Might take a while to fix if they changed the modding support... If you want (and are allowed) you can post the errors, it might help me to start preparing for a fix.

**Comment by theotherbigfoot** [comment] 2024-10-03 20:05
I have enquired and I am not allowed. The exact word they used was 'effectively' so I'm doubtful that what they are telling me is correct but I'm not gonna push my luck.

**Comment by veger** [comment] 2024-10-15 13:32
Besides the rename from `global` -> `storage` (I suppose you already jerry rigged this change?), I do not see breaking things in [this changelog](https://forums.factorio.com/115737).

Since the 'ban' is lifted, are you now able to provide some more details on the error you receive? It might help me to speed up updating the mod for 2.0 when it is out.

**Comment by theotherbigfoot** [comment] 2024-10-17 14:18
Yes I am!! Sorry it's been a few days. These are the three errors we encountered. The first one is probably the source of the problem, the other two are probably the results of us trying to get it working. They may not be relevant.

![error](https://github.com/user-attachments/assets/a55fcd01-2966-4225-ac08-ba84a95db927)
![error2](https://github.com/user-attachments/assets/3a1efac7-2494-4ee1-86fa-b15f1817c953)
![error3](https://github.com/user-attachments/assets/181a0514-abfb-45a8-bebc-4826593999e5)

**Comment by veger** [comment] 2024-10-21 07:51
Sorry I am late as well, I was on a business trip abroad and didn't have time to reply (or even look at)...

I see they changed some of the style/layout entities. I need to find new/better ones. In a few hours 2.0 will be released, so I can see for myself :smile: 
Assuming these are the only changes (besides the ones that were in the 2.0 changelog already), I suppose I can make a 2.0-compatible version today.

**Comment by theotherbigfoot** [comment] 2024-10-21 08:41
That would be pretty flipping incredible. I am struggling without it big time

**Comment by veger** [comment] 2024-10-21 14:39
I released v2.0.0 which seems to be working with (vanilla) Factorio 2.0. (it loads and makes screenshots again)

I did *not* check Space Age yet, so there might be issues.

**Comment by theotherbigfoot** [comment] 2024-10-21 22:31
Loaded up the mod, no issues. It takes screenshots and all the planets and platforms are selectable. 

Only issue I have is that the naming sequence of the final images seems off. I took 3 images and the filenames of the images are as follows: 0025024032, 0025024176, 0025024320. I think they are in the right order, so it isn't a show stopper.

**Comment by veger** [comment] 2024-10-22 08:03
Thank you for your report about the compatibility of Space Age! (I didn't leave Nauvis yet :wink: )

There is a mod option to choose between sequential numbering and ticks for the numbers. With the first (build to mitigate Windows issues) you get numbers starting from 1 and counting up, with the second the mod uses ticks which can be easily recalculated/calibrated to time (being convenient to add a timer or something to the video)

**Comment by theotherbigfoot** [comment] 2024-10-23 10:26
Sequential numbering is selected, but it's still giving me ticks

**Comment by theotherbigfoot** [comment] 2024-10-23 11:25
![ERROR4](https://github.com/user-attachments/assets/59b587d5-2c04-40cd-a4a9-3fc6f3da3ff6)

**Comment by theotherbigfoot** [comment] 2024-10-23 11:26
New error

**Comment by veger** [comment] 2024-10-23 12:10
Did you update to v2.0.1? I think I fixed this one in #62

**Comment by veger** [comment] 2024-10-23 12:10
> Sequential numbering is selected, but it's still giving me ticks

Hm... that is weird, when I am back home, I'll try to reproduce.

**Comment by theotherbigfoot** [comment] 2024-10-23 13:09
Fully updated yes.

I'm on Gleba and if I try and set up a new area or base tracker it instantly crashes.

**Comment by theotherbigfoot** [comment] 2024-10-23 15:19
Ok, my bad, it's working fine. Factorio was updated but the mod wasn't

**Comment by theotherbigfoot** [comment] 2024-10-31 13:21
> > Sequential numbering is selected, but it's still giving me ticks
> 
> Hm... that is weird, when I am back home, I'll try to reproduce.

Did you test this out? I'm still getting ticks and not sequential

**Comment by veger** [comment] 2024-10-31 14:17
Yes I tested it, and just now again.
* I started Factorio with only the TLBE mod enabled and started a new game.
* By default it should use sequential numbering
* Then I just used the default camera and enabled (started) it.
* As a test I paused it after 2 screenshots and when I enabled the screenshot numbers just increased where they left:
![image](https://github.com/user-attachments/assets/09ec8c0a-c6f3-4435-ade4-d04be1ce2805)

It is this particular (mod) setting and enabled the sequential numbering:
![image](https://github.com/user-attachments/assets/71596688-5235-4736-825f-889a00664f06)

**Comment by theotherbigfoot** [comment] 2024-11-08 09:00
I've just started up a new save and the file names are all sequential again. I guess there was possibly an issue with the save file. It was started during the beta phase.

I have a new issue though. When in space the player tracker doesn't follow the player in the game it follows wherever I happen to be looking. It is again not terminal, now I know what it is doing I just won't look anywhere while filming with the player tracker in space, but it might be something worth looking at.

**Comment by veger** [comment] 2024-11-08 11:21
Might be some issue with your (old) save yes... Glad to hear it is 'fixed' now.

> When in space the player tracker doesn't follow the player in the game it follows wherever I happen to be looking

This has been noticed already in #63, so I'll close this one and the other issue can be used to provide the extra feedback/wishes. ATM I was planning to leave it as is, but if you have other/better ideas, please let them know :wink:

**Closed as completed by veger** 2024-11-08 11:21 UTC
